package pojo;
// Generated Jun 16, 2020 6:34:21 PM by Hibernate Tools 4.3.1



/**
 * Chitietphuckhao generated by hbm2java
 */
public class Chitietphuckhao  implements java.io.Serializable {


     private int id;
     private int maPhucKhao;
     private String mssv;
     private String hoTen;
     private String mon;
     private String cotDiem;
     private float diemMongMuon;
     private String lyDo;
     private int trangThai;

    public Chitietphuckhao() {
    }

    public Chitietphuckhao(int id, int maPhucKhao, String mssv, String hoTen, String mon, String cotDiem, float diemMongMuon, String lyDo, int trangThai) {
       this.id = id;
       this.maPhucKhao = maPhucKhao;
       this.mssv = mssv;
       this.hoTen = hoTen;
       this.mon = mon;
       this.cotDiem = cotDiem;
       this.diemMongMuon = diemMongMuon;
       this.lyDo = lyDo;
       this.trangThai = trangThai;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getMaPhucKhao() {
        return this.maPhucKhao;
    }
    
    public void setMaPhucKhao(int maPhucKhao) {
        this.maPhucKhao = maPhucKhao;
    }
    public String getMssv() {
        return this.mssv;
    }
    
    public void setMssv(String mssv) {
        this.mssv = mssv;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getMon() {
        return this.mon;
    }
    
    public void setMon(String mon) {
        this.mon = mon;
    }
    public String getCotDiem() {
        return this.cotDiem;
    }
    
    public void setCotDiem(String cotDiem) {
        this.cotDiem = cotDiem;
    }
    public float getDiemMongMuon() {
        return this.diemMongMuon;
    }
    
    public void setDiemMongMuon(float diemMongMuon) {
        this.diemMongMuon = diemMongMuon;
    }
    public String getLyDo() {
        return this.lyDo;
    }
    
    public void setLyDo(String lyDo) {
        this.lyDo = lyDo;
    }
    public int getTrangThai() {
        return this.trangThai;
    }
    
    public void setTrangThai(int trangThai) {
        this.trangThai = trangThai;
    }




}


