package pojo;
// Generated Jun 6, 2020 4:56:18 PM by Hibernate Tools 4.3.1



/**
 * Chitietphuckhao generated by hbm2java
 */
public class Chitietphuckhao  implements java.io.Serializable {


     private int id;
     private Monhoc monhoc;
     private Phuckhao phuckhao;
     private String mssv;
     private String hoTen;
     private String cotDiem;
     private float diemMongMuon;
     private String lyDo;
     private Integer trangThai;

    public Chitietphuckhao() {
    }

	
    public Chitietphuckhao(int id, Monhoc monhoc, Phuckhao phuckhao, String mssv, String hoTen, String cotDiem, float diemMongMuon) {
        this.id = id;
        this.monhoc = monhoc;
        this.phuckhao = phuckhao;
        this.mssv = mssv;
        this.hoTen = hoTen;
        this.cotDiem = cotDiem;
        this.diemMongMuon = diemMongMuon;
    }
    public Chitietphuckhao(int id, Monhoc monhoc, Phuckhao phuckhao, String mssv, String hoTen, String cotDiem, float diemMongMuon, String lyDo, Integer trangThai) {
       this.id = id;
       this.monhoc = monhoc;
       this.phuckhao = phuckhao;
       this.mssv = mssv;
       this.hoTen = hoTen;
       this.cotDiem = cotDiem;
       this.diemMongMuon = diemMongMuon;
       this.lyDo = lyDo;
       this.trangThai = trangThai;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Monhoc getMonhoc() {
        return this.monhoc;
    }
    
    public void setMonhoc(Monhoc monhoc) {
        this.monhoc = monhoc;
    }
    public Phuckhao getPhuckhao() {
        return this.phuckhao;
    }
    
    public void setPhuckhao(Phuckhao phuckhao) {
        this.phuckhao = phuckhao;
    }
    public String getMssv() {
        return this.mssv;
    }
    
    public void setMssv(String mssv) {
        this.mssv = mssv;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getCotDiem() {
        return this.cotDiem;
    }
    
    public void setCotDiem(String cotDiem) {
        this.cotDiem = cotDiem;
    }
    public float getDiemMongMuon() {
        return this.diemMongMuon;
    }
    
    public void setDiemMongMuon(float diemMongMuon) {
        this.diemMongMuon = diemMongMuon;
    }
    public String getLyDo() {
        return this.lyDo;
    }
    
    public void setLyDo(String lyDo) {
        this.lyDo = lyDo;
    }
    public Integer getTrangThai() {
        return this.trangThai;
    }
    
    public void setTrangThai(Integer trangThai) {
        this.trangThai = trangThai;
    }




}


