package pojo;
// Generated Jun 12, 2020 11:03:16 PM by Hibernate Tools 4.3.1



/**
 * Lophoc generated by hbm2java
 */
public class Lophoc  implements java.io.Serializable {


     private String maLop;
     private String tenLop;
     private int laLopHoc;

    public Lophoc() {
    }

    public Lophoc(String maLop, String tenLop, int laLopHoc) {
       this.maLop = maLop;
       this.tenLop = tenLop;
       this.laLopHoc = laLopHoc;
    }
   
    public String getMaLop() {
        return this.maLop;
    }
    
    public void setMaLop(String maLop) {
        this.maLop = maLop;
    }
    public String getTenLop() {
        return this.tenLop;
    }
    
    public void setTenLop(String tenLop) {
        this.tenLop = tenLop;
    }
    public int getLaLopHoc() {
        return this.laLopHoc;
    }
    
    public void setLaLopHoc(int laLopHoc) {
        this.laLopHoc = laLopHoc;
    }




}


