package pojo;
// Generated Jun 12, 2020 11:03:16 PM by Hibernate Tools 4.3.1



/**
 * Loptheomon generated by hbm2java
 */
public class Loptheomon  implements java.io.Serializable {


     private String maLopTheoMon;
     private String mon;
     private String lop;
     private int sinhVien;
     private float diemGk;
     private float diemCk;
     private float diemKhac;
     private float diemTong;

    public Loptheomon() {
    }

    public Loptheomon(String maLopTheoMon, String mon, String lop, int sinhVien, float diemGk, float diemCk, float diemKhac, float diemTong) {
       this.maLopTheoMon = maLopTheoMon;
       this.mon = mon;
       this.lop = lop;
       this.sinhVien = sinhVien;
       this.diemGk = diemGk;
       this.diemCk = diemCk;
       this.diemKhac = diemKhac;
       this.diemTong = diemTong;
    }
   
    public String getMaLopTheoMon() {
        return this.maLopTheoMon;
    }
    
    public void setMaLopTheoMon(String maLopTheoMon) {
        this.maLopTheoMon = maLopTheoMon;
    }
    public String getMon() {
        return this.mon;
    }
    
    public void setMon(String mon) {
        this.mon = mon;
    }
    public String getLop() {
        return this.lop;
    }
    
    public void setLop(String lop) {
        this.lop = lop;
    }
    public int getSinhVien() {
        return this.sinhVien;
    }
    
    public void setSinhVien(int sinhVien) {
        this.sinhVien = sinhVien;
    }
    public float getDiemGk() {
        return this.diemGk;
    }
    
    public void setDiemGk(float diemGk) {
        this.diemGk = diemGk;
    }
    public float getDiemCk() {
        return this.diemCk;
    }
    
    public void setDiemCk(float diemCk) {
        this.diemCk = diemCk;
    }
    public float getDiemKhac() {
        return this.diemKhac;
    }
    
    public void setDiemKhac(float diemKhac) {
        this.diemKhac = diemKhac;
    }
    public float getDiemTong() {
        return this.diemTong;
    }
    
    public void setDiemTong(float diemTong) {
        this.diemTong = diemTong;
    }




}


