package pojo;
// Generated Jun 6, 2020 4:56:18 PM by Hibernate Tools 4.3.1



/**
 * Loptheomon generated by hbm2java
 */
public class Loptheomon  implements java.io.Serializable {


     private int id;
     private Lophoc lophoc;
     private Sinhvien sinhvien;
     private String maLopTheoMon;
     private String mon;
     private float diemGk;
     private float diemCk;
     private float diemKhac;
     private float diemTong;

    public Loptheomon() {
    }

    public Loptheomon(int id, Lophoc lophoc, Sinhvien sinhvien, String maLopTheoMon, String mon, float diemGk, float diemCk, float diemKhac, float diemTong) {
       this.id = id;
       this.lophoc = lophoc;
       this.sinhvien = sinhvien;
       this.maLopTheoMon = maLopTheoMon;
       this.mon = mon;
       this.diemGk = diemGk;
       this.diemCk = diemCk;
       this.diemKhac = diemKhac;
       this.diemTong = diemTong;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Lophoc getLophoc() {
        return this.lophoc;
    }
    
    public void setLophoc(Lophoc lophoc) {
        this.lophoc = lophoc;
    }
    public Sinhvien getSinhvien() {
        return this.sinhvien;
    }
    
    public void setSinhvien(Sinhvien sinhvien) {
        this.sinhvien = sinhvien;
    }
    public String getMaLopTheoMon() {
        return this.maLopTheoMon;
    }
    
    public void setMaLopTheoMon(String maLopTheoMon) {
        this.maLopTheoMon = maLopTheoMon;
    }
    public String getMon() {
        return this.mon;
    }
    
    public void setMon(String mon) {
        this.mon = mon;
    }
    public float getDiemGk() {
        return this.diemGk;
    }
    
    public void setDiemGk(float diemGk) {
        this.diemGk = diemGk;
    }
    public float getDiemCk() {
        return this.diemCk;
    }
    
    public void setDiemCk(float diemCk) {
        this.diemCk = diemCk;
    }
    public float getDiemKhac() {
        return this.diemKhac;
    }
    
    public void setDiemKhac(float diemKhac) {
        this.diemKhac = diemKhac;
    }
    public float getDiemTong() {
        return this.diemTong;
    }
    
    public void setDiemTong(float diemTong) {
        this.diemTong = diemTong;
    }




}


