package pojo;
// Generated Jun 6, 2020 4:56:18 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Monhoc generated by hbm2java
 */
public class Monhoc  implements java.io.Serializable {


     private String maMon;
     private Lophoc lophoc;
     private String tenMon;
     private String phongHoc;
     private Set chitietphuckhaos = new HashSet(0);

    public Monhoc() {
    }

	
    public Monhoc(String maMon, Lophoc lophoc, String tenMon, String phongHoc) {
        this.maMon = maMon;
        this.lophoc = lophoc;
        this.tenMon = tenMon;
        this.phongHoc = phongHoc;
    }
    public Monhoc(String maMon, Lophoc lophoc, String tenMon, String phongHoc, Set chitietphuckhaos) {
       this.maMon = maMon;
       this.lophoc = lophoc;
       this.tenMon = tenMon;
       this.phongHoc = phongHoc;
       this.chitietphuckhaos = chitietphuckhaos;
    }
   
    public String getMaMon() {
        return this.maMon;
    }
    
    public void setMaMon(String maMon) {
        this.maMon = maMon;
    }
    public Lophoc getLophoc() {
        return this.lophoc;
    }
    
    public void setLophoc(Lophoc lophoc) {
        this.lophoc = lophoc;
    }
    public String getTenMon() {
        return this.tenMon;
    }
    
    public void setTenMon(String tenMon) {
        this.tenMon = tenMon;
    }
    public String getPhongHoc() {
        return this.phongHoc;
    }
    
    public void setPhongHoc(String phongHoc) {
        this.phongHoc = phongHoc;
    }
    public Set getChitietphuckhaos() {
        return this.chitietphuckhaos;
    }
    
    public void setChitietphuckhaos(Set chitietphuckhaos) {
        this.chitietphuckhaos = chitietphuckhaos;
    }




}


