package pojo;
// Generated Jun 12, 2020 11:03:16 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Phuckhao generated by hbm2java
 */
public class Phuckhao  implements java.io.Serializable {


     private int maPhucKhao;
     private Date ngayBatDau;
     private Date ngayKetThuc;

    public Phuckhao() {
    }

    public Phuckhao(int maPhucKhao, Date ngayBatDau, Date ngayKetThuc) {
       this.maPhucKhao = maPhucKhao;
       this.ngayBatDau = ngayBatDau;
       this.ngayKetThuc = ngayKetThuc;
    }
   
    public int getMaPhucKhao() {
        return this.maPhucKhao;
    }
    
    public void setMaPhucKhao(int maPhucKhao) {
        this.maPhucKhao = maPhucKhao;
    }
    public Date getNgayBatDau() {
        return this.ngayBatDau;
    }
    
    public void setNgayBatDau(Date ngayBatDau) {
        this.ngayBatDau = ngayBatDau;
    }
    public Date getNgayKetThuc() {
        return this.ngayKetThuc;
    }
    
    public void setNgayKetThuc(Date ngayKetThuc) {
        this.ngayKetThuc = ngayKetThuc;
    }




}


