package pojo;
// Generated Jun 6, 2020 4:56:18 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sinhvien generated by hbm2java
 */
public class Sinhvien  implements java.io.Serializable {


     private int maSv;
     private Lophoc lophoc;
     private String mssv;
     private String hoTen;
     private String gioiTinh;
     private String cmnd;
     private String matKhau;
     private Set loptheomons = new HashSet(0);
     private Set loptheomons_1 = new HashSet(0);

    public Sinhvien() {
    }

	
    public Sinhvien(int maSv, Lophoc lophoc, String mssv, String hoTen, String gioiTinh, String cmnd, String matKhau) {
        this.maSv = maSv;
        this.lophoc = lophoc;
        this.mssv = mssv;
        this.hoTen = hoTen;
        this.gioiTinh = gioiTinh;
        this.cmnd = cmnd;
        this.matKhau = matKhau;
    }
    public Sinhvien(int maSv, Lophoc lophoc, String mssv, String hoTen, String gioiTinh, String cmnd, String matKhau, Set loptheomons, Set loptheomons_1) {
       this.maSv = maSv;
       this.lophoc = lophoc;
       this.mssv = mssv;
       this.hoTen = hoTen;
       this.gioiTinh = gioiTinh;
       this.cmnd = cmnd;
       this.matKhau = matKhau;
       this.loptheomons = loptheomons;
       this.loptheomons_1 = loptheomons_1;
    }
   
    public int getMaSv() {
        return this.maSv;
    }
    
    public void setMaSv(int maSv) {
        this.maSv = maSv;
    }
    public Lophoc getLophoc() {
        return this.lophoc;
    }
    
    public void setLophoc(Lophoc lophoc) {
        this.lophoc = lophoc;
    }
    public String getMssv() {
        return this.mssv;
    }
    
    public void setMssv(String mssv) {
        this.mssv = mssv;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(String gioiTinh) {
        this.gioiTinh = gioiTinh;
    }
    public String getCmnd() {
        return this.cmnd;
    }
    
    public void setCmnd(String cmnd) {
        this.cmnd = cmnd;
    }
    public String getMatKhau() {
        return this.matKhau;
    }
    
    public void setMatKhau(String matKhau) {
        this.matKhau = matKhau;
    }
    public Set getLoptheomons() {
        return this.loptheomons;
    }
    
    public void setLoptheomons(Set loptheomons) {
        this.loptheomons = loptheomons;
    }
    public Set getLoptheomons_1() {
        return this.loptheomons_1;
    }
    
    public void setLoptheomons_1(Set loptheomons_1) {
        this.loptheomons_1 = loptheomons_1;
    }




}


