package pojo;
// Generated Jun 17, 2020 9:20:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sinhvien generated by hbm2java
 */
public class Sinhvien  implements java.io.Serializable {


     private String mssv;
     private Lophoc lophoc;
     private String hoTen;
     private String gioiTinh;
     private String cmnd;
     private String matKhau;
     private Set loptheomons = new HashSet(0);

    public Sinhvien() {
    }

	
    public Sinhvien(String mssv, Lophoc lophoc, String hoTen, String gioiTinh, String cmnd, String matKhau) {
        this.mssv = mssv;
        this.lophoc = lophoc;
        this.hoTen = hoTen;
        this.gioiTinh = gioiTinh;
        this.cmnd = cmnd;
        this.matKhau = matKhau;
    }
    public Sinhvien(String mssv, Lophoc lophoc, String hoTen, String gioiTinh, String cmnd, String matKhau, Set loptheomons) {
       this.mssv = mssv;
       this.lophoc = lophoc;
       this.hoTen = hoTen;
       this.gioiTinh = gioiTinh;
       this.cmnd = cmnd;
       this.matKhau = matKhau;
       this.loptheomons = loptheomons;
    }
   
    public String getMssv() {
        return this.mssv;
    }
    
    public void setMssv(String mssv) {
        this.mssv = mssv;
    }
    public Lophoc getLophoc() {
        return this.lophoc;
    }
    
    public void setLophoc(Lophoc lophoc) {
        this.lophoc = lophoc;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(String gioiTinh) {
        this.gioiTinh = gioiTinh;
    }
    public String getCmnd() {
        return this.cmnd;
    }
    
    public void setCmnd(String cmnd) {
        this.cmnd = cmnd;
    }
    public String getMatKhau() {
        return this.matKhau;
    }
    
    public void setMatKhau(String matKhau) {
        this.matKhau = matKhau;
    }
    public Set getLoptheomons() {
        return this.loptheomons;
    }
    
    public void setLoptheomons(Set loptheomons) {
        this.loptheomons = loptheomons;
    }




}


