/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import dao.*;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pojo.Lophoc;
import pojo.Sinhvien;

/**
 *
 * @author Chen-Yang
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        //setDefaultCloseOperation(Login.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDangNhap = new javax.swing.JLabel();
        lblMatKhau = new javax.swing.JLabel();
        lblTenDangNhap = new javax.swing.JLabel();
        txtTenDN = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JPasswordField();
        cbxGV = new javax.swing.JCheckBox();
        btnDangNhap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setName("Login"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDangNhap.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDangNhap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDangNhap.setText("ĐĂNG NHẬP");
        getContentPane().add(lblDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 13, 140, 33));

        lblMatKhau.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblMatKhau.setText("Mật khẩu");
        getContentPane().add(lblMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 140, 114, 29));

        lblTenDangNhap.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblTenDangNhap.setText("Tên đăng nhập");
        getContentPane().add(lblTenDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 74, 115, 29));

        txtTenDN.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(txtTenDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 74, 215, 30));

        txtMatKhau.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 140, 213, 30));

        cbxGV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cbxGV.setText("Là giáo viên");
        getContentPane().add(cbxGV, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 201, -1, -1));

        btnDangNhap.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnDangNhap.setText("ĐĂNG NHẬP");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        getContentPane().add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 248, 133, 34));

        setSize(new java.awt.Dimension(463, 380));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        String path="";
        Account acc = new Account();
        List<Account> dsAcc;
        acc.setTenDN(txtTenDN.getText());
        acc.setMatKhau(txtMatKhau.getText());
        if(txtTenDN.getText().equals("") || txtMatKhau.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane,"Bạn cần nhập đầy đủ thông tin");
        }
        else if(txtTenDN.getText()!="" && txtMatKhau.getText()!="") {
            if(cbxGV.isSelected()) {
                path = "data/gvAccount.csv";
                try {
                    dsAcc =  AccountDAO.DocAccount(path);
                    if(AccountDAO.Search(acc, dsAcc)==true) {
                        Dashboard db = new Dashboard( acc);
                        
                        db.setVisible(true);
                        //DoiMatKhau dmk = new DoiMatKhau(acc);
                        //dmk.setVisible(false);
                    }
                    else {
                        JOptionPane.showMessageDialog(rootPane,"Tên đăng nhập hoặc mật khẩu không đúng!");
                    }
                } catch (IOException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
            }
            else if(!cbxGV.isSelected()){
                path = "data/svAccount.csv";
                try {
                    dsAcc =  AccountDAO.DocAccount(path);
                    if(AccountDAO.Search(acc, dsAcc)==true) {
                        Dashboard db = new Dashboard(acc);
                        db.setVisible(true);
                    }
                    else {
                        JOptionPane.showMessageDialog(rootPane,"Tên đăng nhập hoặc mật khẩu không đúng!");
                    }
                } catch (IOException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            } 
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDangNhapActionPerformed

    public String layTenDN() {
        return txtTenDN.getText();
    }
    public String layMatKhau() {
        return txtMatKhau.getText();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JCheckBox cbxGV;
    private javax.swing.JLabel lblDangNhap;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblTenDangNhap;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTenDN;
    // End of variables declaration//GEN-END:variables
}
