/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import dao.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.Chitietphuckhao;
import pojo.Phuckhao;

/**
 *
 * @author Chen-Yang
 */
public class QuanlyPhucKhao extends javax.swing.JFrame {
    DefaultTableModel model;
    public static int index;
    /**
     * Creates new form QuanlyPhucKhao
     */
    public QuanlyPhucKhao() {
        initComponents();
        setDefaultCloseOperation(XemDiem.DISPOSE_ON_CLOSE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtBatDau = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtKetThuc = new javax.swing.JTextField();
        btnCapNhat = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbbLoc = new javax.swing.JComboBox<>();
        btnLoc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbeXem = new javax.swing.JTable();
        btnCapNhatTT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý phúc khảo");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Quản lý phúc khảo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 183, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Ngày bắt đầu:");

        txtBatDau.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Ngày kết thúc:");

        txtKetThuc.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        btnCapNhat.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBatDau, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtKetThuc, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Danh sách sinh viên phúc khảo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 149, 251, 30));

        cbbLoc.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cbbLoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Chưa xem", "Đã cập nhật điểm", "Không cập nhật điểm" }));
        getContentPane().add(cbbLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 149, 210, 30));

        btnLoc.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnLoc.setText("Lọc");
        btnLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocActionPerformed(evt);
            }
        });
        getContentPane().add(btnLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 150, 124, -1));

        tbeXem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbeXem.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbeXemAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tbeXem);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 1037, 157));

        btnCapNhatTT.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnCapNhatTT.setText("Cập nhật trạng thái");
        btnCapNhatTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatTTActionPerformed(evt);
            }
        });
        getContentPane().add(btnCapNhatTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 193, -1));

        setSize(new java.awt.Dimension(1079, 508));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        Phuckhao pk = new Phuckhao();

        if (txtBatDau.getText().equals("") || txtKetThuc.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Bạn cần nhập đầy đủ ngày bắt đầu và kết thúc");
        }
        if (txtBatDau.getText() != null && txtKetThuc != null) {
            Date ngBatDau = null;
            Date ngKetThuc = null;
            try{
                ngBatDau = new SimpleDateFormat("dd/MM/yyyy").parse(txtBatDau.getText()); 
            }catch(ParseException pe){
                pe.printStackTrace();
            }
            try {
                ngKetThuc = new SimpleDateFormat("dd/MM/yyyy").parse(txtKetThuc.getText());
            } catch (ParseException pe) {
                pe.printStackTrace();
            }
            SimpleDateFormat ft = new SimpleDateFormat();
            String[] batDau = ft.format(ngBatDau).toString().split("-");
            String[] ketThuc = ft.format(ngKetThuc).toString().split("-");
            if(ngBatDau.compareTo(ngKetThuc)<0) {
                pk.setMaPhucKhao(Integer.parseInt(batDau[0]+batDau[1]+batDau[2]+ketThuc[0]+ketThuc[1]+ketThuc[2]));
                pk.setNgayBatDau(ngBatDau);
                pk.setNgayKetThuc(ngKetThuc);
                if (PhucKhaoDAO.themPhucKhao(pk) == true) {
                    JOptionPane.showMessageDialog(rootPane, "Tạo phúc khảo điểm thành công");
                }
                else {
                    JOptionPane.showMessageDialog(rootPane, "Tạo phúc khảo điểm thất bại vì đã tồn tại");
                }
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Ngày kết thúc phải lớn hơn ngày bắt đầu");
            }
            
            
//            pk.setMaPhucKhao(1);
//            if(PhucKhaoDAO.themPhucKhao(pk)==true) {
//                JOptionPane.showMessageDialog(rootPane, "Tạo phúc khảo điểm thành công");
//            }
//            else {
//                JOptionPane.showMessageDialog(rootPane, "Tạo phúc khảo điểm thất bại");
//            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void tbeXemAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbeXemAncestorAdded
        
        // TODO add your handling code here:
    }//GEN-LAST:event_tbeXemAncestorAdded

    private void btnLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocActionPerformed
        showResult();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLocActionPerformed

    private void btnCapNhatTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatTTActionPerformed
        index = tbeXem.getSelectedRow();
        if(index==-1) {
            JOptionPane.showMessageDialog(rootPane,"Hãy chọn dòng cần cập nhật");
        }
        else {
            
            CapNhatPhucKhao cnpk = new CapNhatPhucKhao(model,index);
            cnpk.setVisible(true);


        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCapNhatTTActionPerformed

    public void showResult() {
        String loc = (String) cbbLoc.getSelectedItem().toString();
        List<Chitietphuckhao> ds = DangKiPhucKhaoDAO.layDachSachDangKiPhucKhao();
        model = new DefaultTableModel();
        int check_ = 0;
        model.setColumnIdentifiers(new Object[]{
            "STT", "MSSV", "Họ tên", "Môn", "Cột điểm phúc khảo", "Điểm mong muốn", "Lý do", "Tình trạng"
        });
        if (loc.compareTo("Tất cả") == 0) {
            int j = 1;
            ArrayList arrRows = new ArrayList();
            if (ds.size() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Chưa có dữ liệu");
            }
            for (int i = 0; i < ds.size(); i++) {
                Chitietphuckhao ct = ds.get(i);
                //j=i+1;
                arrRows.add(j++);
                arrRows.add(ct.getMssv());
                arrRows.add(ct.getHoTen());
                arrRows.add(ct.getMonhoc().getMaMon());
                arrRows.add(ct.getCotDiem());
                arrRows.add(ct.getDiemMongMuon());
                arrRows.add(ct.getLyDo());
                if (ct.getTrangThai() == 0) {
                    arrRows.add("Chưa xem");
                } else if (ct.getTrangThai() == 1) {
                    arrRows.add("Đã cập nhật điểm");
                } else if (ct.getTrangThai() == -1) {
                    arrRows.add("Không cập nhật điểm");
                }

                model.addRow(arrRows.toArray());
                arrRows.clear();
            }

            tbeXem.setModel(model);
            if (tbeXem.getRowCount() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Chưa có dữ liệu");
            }
        } else if (loc.compareTo("Chưa xem") == 0) {
            int j = 1;
            ArrayList arrRows = new ArrayList();
            for (int i = 0; i < ds.size(); i++) {
                Chitietphuckhao ct = ds.get(i);
                //j=i+1;
                if (ct.getTrangThai() == 0) {
                    arrRows.add(j++);
                    arrRows.add(ct.getMssv());
                    arrRows.add(ct.getHoTen());
                    arrRows.add(ct.getMonhoc().getMaMon());
                    arrRows.add(ct.getCotDiem());
                    arrRows.add(ct.getDiemMongMuon());
                    arrRows.add(ct.getLyDo());
                    arrRows.add("Chưa xem");
                }

                model.addRow(arrRows.toArray());
                arrRows.clear();
            }

            tbeXem.setModel(model);
            if (tbeXem.getRowCount() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Chưa có dữ liệu");
            }
        } else if (loc.compareTo("Đã cập nhật điểm") == 0) {
            int j = 1;
            ArrayList arrRows = new ArrayList();
            for (int i = 0; i < ds.size(); i++) {
                Chitietphuckhao ct = ds.get(i);
                //j=i+1;
                if (ct.getTrangThai() == 1) {
                    arrRows.add(j++);
                    arrRows.add(ct.getMssv());
                    arrRows.add(ct.getHoTen());
                    arrRows.add(ct.getMonhoc().getMaMon());
                    arrRows.add(ct.getCotDiem());
                    arrRows.add(ct.getDiemMongMuon());
                    arrRows.add(ct.getLyDo());
                    arrRows.add("Đã cập nhật điểm");
                }

                model.addRow(arrRows.toArray());
                arrRows.clear();
            }
            tbeXem.setModel(model);
            if (tbeXem.getRowCount() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Chưa có dữ liệu");
            }
        } else if (loc.compareTo("Không cập nhật điểm") == 0) {
            int j = 1;
            ArrayList arrRows = new ArrayList();
            for (int i = 0; i < ds.size(); i++) {
                Chitietphuckhao ct = ds.get(i);
                //j=i+1;
                if (ct.getTrangThai() == -1) {
                    arrRows.add(j++);
                    arrRows.add(ct.getMssv());
                    arrRows.add(ct.getHoTen());
                    arrRows.add(ct.getMonhoc().getMaMon());
                    arrRows.add(ct.getCotDiem());
                    arrRows.add(ct.getDiemMongMuon());
                    arrRows.add(ct.getLyDo());
                    arrRows.add("Không cập nhật điểm");
                }

                model.addRow(arrRows.toArray());
                arrRows.clear();
            }
            tbeXem.setModel(model);
            if (tbeXem.getRowCount() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Chưa có dữ liệu");
            }
        }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanlyPhucKhao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanlyPhucKhao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanlyPhucKhao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanlyPhucKhao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanlyPhucKhao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnCapNhatTT;
    private javax.swing.JButton btnLoc;
    private javax.swing.JComboBox<String> cbbLoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbeXem;
    private javax.swing.JTextField txtBatDau;
    private javax.swing.JTextField txtKetThuc;
    // End of variables declaration//GEN-END:variables
}
