/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import dao.*;
import dao.*;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.lang.String;
import pojo.Loptheomon;
import pojo.Monhoc;
import pojo.Sinhvien;

/**
 *
 * @author Chen-Yang
 */
public class QuanLyDiem extends javax.swing.JFrame {
    String filePath;
    DefaultTableModel model;
    Loptheomon ltm;
    /**
     * Creates new form QuanLyDiem
     */
    public QuanLyDiem() {
        initComponents();
        setDefaultCloseOperation(XemDiem.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtImport = new javax.swing.JTextField();
        btnChonFile = new javax.swing.JButton();
        btnImport = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cbbLopDS = new javax.swing.JComboBox<>();
        cbbMonDS = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        btnTaiSV = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbeDS = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTong = new javax.swing.JTextField();
        txtDau = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtRot = new javax.swing.JTextField();
        btnSuaDiem = new javax.swing.JButton();
        btnXoaSV = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý điểm");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Thêm sinh viên vào môn");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 212, 29));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Import điểm");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 0, 212, 29));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Lớp");

        jComboBox5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Sinh viên");

        jComboBox6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Môn");

        jComboBox7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton4.setText("Thêm");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 35, 466, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtImport.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        btnChonFile.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnChonFile.setText("Chọn file");
        btnChonFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonFileActionPerformed(evt);
            }
        });

        btnImport.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnImport.setText("Import");
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(txtImport, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnChonFile, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(btnImport, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImport, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChonFile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(btnImport)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 35, -1, 283));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Lớp");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 367, 42, 30));

        cbbLopDS.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cbbLopDS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn", "17HCB", "18HCB" }));
        cbbLopDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbLopDSActionPerformed(evt);
            }
        });
        getContentPane().add(cbbLopDS, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 367, 340, 30));

        cbbMonDS.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cbbMonDS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn" }));
        cbbMonDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMonDSActionPerformed(evt);
            }
        });
        getContentPane().add(cbbMonDS, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 367, 319, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Môn");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 367, 43, 30));

        btnTaiSV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnTaiSV.setText("Tải danh sách SV");
        btnTaiSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiSVActionPerformed(evt);
            }
        });
        getContentPane().add(btnTaiSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(828, 367, 176, 30));

        tbeDS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbeDS.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbeDSAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tbeDS);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 415, 992, 180));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("Tổng số lượng sinh viên:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 613, 181, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setText("Tỉ lệ sinh viên đậu: ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 650, 181, 30));

        txtTong.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(txtTong, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 613, 104, 30));

        txtDau.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(txtDau, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 650, 104, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setText("Tỉ lệ sinh viên rớt: ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 650, 181, 30));

        txtRot.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(txtRot, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 650, 104, 30));

        btnSuaDiem.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnSuaDiem.setText("Sửa điểm");
        btnSuaDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaDiemActionPerformed(evt);
            }
        });
        getContentPane().add(btnSuaDiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(724, 613, 122, 30));

        btnXoaSV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnXoaSV.setText("Xóa sinh viên");
        btnXoaSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSVActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoaSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(864, 613, 140, 30));

        setSize(new java.awt.Dimension(1034, 740));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChonFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonFileActionPerformed
        JFileChooser c = new JFileChooser("data");
        int rVal = c.showOpenDialog(null);
        if (rVal == JFileChooser.APPROVE_OPTION) {
        String filename = c.getSelectedFile().getName();
        String dir = c.getCurrentDirectory().toString();
        filePath = dir+"\\"+filename;
        txtImport.setText(filePath);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChonFileActionPerformed

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        if(filePath==null) {
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn file");
        }
        else {
            try {
                if(DiemDAO.updateDiemImport(filePath)==true) {
                    JOptionPane.showMessageDialog(rootPane, "Import danh sách điểm thành công");
                }
                else {
                    JOptionPane.showMessageDialog(rootPane, "Không thể import");
                }
            } catch (IOException ex) {
                Logger.getLogger(ImportSinhVien.class.getName()).log(Level.SEVERE, null, ex);
            }
            //System.exit(0); 
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImportActionPerformed

    private void cbbLopDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbLopDSActionPerformed
        String lop = (String) cbbLopDS.getSelectedItem().toString();
        List<Monhoc> dsMon = ThoiKhoaBieuDAO.layDachSachTKB();
        //cbbMonDS = new JComboBox();
        cbbMonDS.removeAllItems();
        for(int i=0;i<dsMon.size();i++) {
            
            if(lop.compareTo(dsMon.get(i).getLophoc().getMaLop())==0) {
                //cbbMonDS = new JComboBox();
                //cbbMonDS.removeAllItems();
                cbbMonDS.addItem(dsMon.get(i).getTenMon()+" - "+dsMon.get(i).getMaMon());
                cbbMonDS.setVisible(true);
            }
            
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbLopDSActionPerformed

    
    
    private void cbbMonDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMonDSActionPerformed
//        String lop = (String) cbbLopDS.getSelectedItem().toString();
//        List<Monhoc> dsMon = ThoiKhoaBieuDAO.layDachSachTKB();
//        for(int i=0;i<dsMon.size();i++) {
//            if(lop.compareTo(dsMon.get(i).getLophoc().getMaLop())==0) {
//                cbbMonDS.addItem(dsMon.get(i).getTenMon());
//            }
//        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbMonDSActionPerformed

    private void btnTaiSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiSVActionPerformed
        showResult();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTaiSVActionPerformed

    private void tbeDSAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbeDSAncestorAdded
        
        // TODO add your handling code here:
    }//GEN-LAST:event_tbeDSAncestorAdded

    private void btnSuaDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaDiemActionPerformed

        int index = tbeDS.getSelectedRow();
        if(index==-1) {
            JOptionPane.showMessageDialog(rootPane,"Hãy chọn dòng cần sửa");
        }
        else {
            
            int id = (int) model.getValueAt(index,1);
            ltm = DiemDAO.layThongTinLopTheoMon(id);
            CapNhatDiem cnd = new CapNhatDiem(ltm);
            cnd.setVisible(true);
        }
        
        
        showResult();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaDiemActionPerformed

    private void btnXoaSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSVActionPerformed
        int index = tbeDS.getSelectedRow();
        if(index==-1) {
            JOptionPane.showMessageDialog(rootPane,"Hãy chọn dòng cần xóa");
        }
        else {
            
            int id = (int) model.getValueAt(index,1);
            DiemDAO.xoaLopTheoMon(id);
            showResult();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaSVActionPerformed

    public void showResult() {
        String lop = (String) cbbLopDS.getSelectedItem().toString();
        String mon = (String) cbbMonDS.getSelectedItem().toString();
        
        List<Loptheomon> ds = DiemDAO.layDachSachLopTheoMon();
        model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[] {
            "STT","ID","MSSV","Họ tên","Điểm GK","Điểm CK","Điểm khác","Điểm tổng","Tình trạng"
        });
        
        int j;
        ArrayList arrRows = new ArrayList();
        //System.out.println(mon);
        for(int i=0;i<ds.size();i++) {
            //Loptheomon ltm = ds.get(i);
            //System.out.println(ds.get(i).getMonhoc().getMaMon());
            if(ds.get(i).getLophoc().getMaLop().compareTo(lop)==0) {
                
                if(mon.contains(ds.get(i).getMonhoc().getMaMon())==true) {
                    //System.out.println("Vô được if nhỏ");
                    j=i+1;
                    arrRows.add(j);
                    arrRows.add(ds.get(i).getId());
                    
                    //Loptheomon sv = DiemDAO.layThongTinHocSinhLopTheoMon(ds.get(i).getSinhvien());
                    arrRows.add(ds.get(i).getSinhvien().getMssv());
                    Sinhvien sv = SinhVienDAO.layThongTinSinhVien(ds.get(i).getSinhvien().getMssv());
                    arrRows.add(sv.getHoTen());
                    arrRows.add(ds.get(i).getDiemGk());
                    arrRows.add(ds.get(i).getDiemCk());
                    arrRows.add(ds.get(i).getDiemKhac());
                    arrRows.add(ds.get(i).getDiemTong());
                    if(ds.get(i).getDiemTong()>=5) {
                        arrRows.add("Đậu");
                    }
                    else {
                        arrRows.add("Rớt");
                    }

                    model.addRow(arrRows.toArray());
                    arrRows.clear();
                }
            }
        }
        tbeDS.setModel(model);
        
        //thong ke phan tram dau rot
        int row = model.getRowCount();
        String rowTemp = String.valueOf(row);
        //List<String> tinhTrang = null;
        int dau=0;
        for(int jj=0;jj<row;jj++) {
            String tinhtrang = (String) model.getValueAt(jj, 8);
            
            if(tinhtrang.compareTo("Đậu")==0) {
                dau++;
            }
        }
        float phanTramDau = dau*100/row;
        
        txtTong.setText(rowTemp);
        txtDau.setText(String.valueOf(phanTramDau)+"%");
        txtRot.setText(String.valueOf(100-phanTramDau)+"%");
        txtTong.setVisible(true);
        txtDau.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyDiem().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonFile;
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnSuaDiem;
    private javax.swing.JButton btnTaiSV;
    private javax.swing.JButton btnXoaSV;
    private javax.swing.JComboBox<String> cbbLopDS;
    private javax.swing.JComboBox<String> cbbMonDS;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbeDS;
    private javax.swing.JTextField txtDau;
    private javax.swing.JTextField txtImport;
    private javax.swing.JTextField txtRot;
    private javax.swing.JTextField txtTong;
    // End of variables declaration//GEN-END:variables
}
